sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: Rk3bZs9QJI5TjLYxKQXBb+li3M2Jn4WZDSdxbPuhBCnjClROXzyZzBbKDCdaQLXYbyg/3VKDiDsTt8g7w0DcQ11eHG0lVqxvCwCBZe1sKVCPrGlv/KbzmVYMcD87SrJnIYnquy00I1ZKPganSOaprEffdX1kCMZ/xV7wBJTf7St1Gl/jK6ZJtpTzwiprROEFWVzkPqTjXGF6vwvRkT04FpMtlbuRSfBCTTtdjzFd2GHVYC+inRlsd33ivTqv7yyvgdmOzzYn45x0dH1bR1O0748qw/e5Y7KtIDbbb+3zuabnozLPgaJvLsl6XroUdNmuf6UcXG4RzOdBEMT483HW5D5RzDWwQ8RJARcNSnV007bdgGFZzxj5oJRsa7iJIKETKcrPN3fHuAPjF8eu53jZTfR/vEWjOFXjtJoD+HtEJlLEJpG+wJ543Acdbrr+JXZBq4mq3gXLnKsHDLUuipgXClXdFIq0ctjJKN8RaA8DXrtYHe7VMYw/SYcnPfy3gMvp9xZCZ1aE1GOON83xuBUdlRDQljYRjFULM1SdOnEoXsjSAtLw4lZKA8b5ENjyLieIm2Zm7MgARPxq4kECofWxLCjdyK16OHET3+QpTbaqA1ixfGHbPolwFhSNQUHuz2H/2USKMRGbjcU+Jy4RIYHfGtDvrvfDOrGc+1mC6CMIMs0=
    - secure: btVKUynoshJJsEZAxT/lvIMR+JBCgDz8miUZI0Lj/rAqx5BIaQKNMYzDmm9sFAHdLkAnfx4KzO7bVhblgZ4etJtKt/mXYQ8vSx7IA/y4omhDT0TqkRFb9mZKPoSTlDQCIaj7ZGSfna/8/WotpqgWcrRh5GYW+zpGKVOvmWVwYoftptdSUJ2cqmEZjO0bQkZgio/nKkr8cgDv4qGzR3Fe6gM5sUwOkb/VJ9WiplYuB0ucd4JjnyQ+NajFrR5JpTTq3eZ6G/15xTB08y+xs882Yl8A6FM+PIZXlEvV3G2w5wxX9fLjt0AnHBHZAmlL4RJACtdelomg0gaYKFwDvCXaHKRkWD1rxBs2gUcLwJsKzdTjLuzVxBBEP3OxTLrPOpba099pL/mbWoTcrNDV4/wPzmWErP3u3nPpuGn9k8IMyV9v1fppcv8NMShXw5N6TlUYzYfsUpfnGyYzAc+sPzklLRJ6k7mYMu4VciUfyS/hLjQO+2adhpU7wx39PYtq3UAOQkm40IpMmD4SUvsPBJcwmyqBGYAbbT5rNxzPoMW0+gUh9U3Xe3V3q4kl3e7e2dtjgScna5yMdrW//xxSJXJkKrj+reDzoMvgqucxeaXJLNtyty4p8nmLMhpTDwSb4oAd+PlC72gTEZezXQKY1VJhjSpZoWCcvJTbE6GDS0J7IuA=
